name: flutter_cache_manager_firebase
description: CacheManager implementation for firebase_storage. Uses the gs:// as key and translates to https://
version: 2.0.1
homepage: https://github.com/Baseflow/flutter_cache_manager
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager:
    git:
      url: https://github.com/tentram/flutter_cache_manager
      ref: develop
      path: flutter_cache_manager

  firebase_storage: ">=8.0.0 <12.0.0"
  path_provider: ^2.1.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
