name: flutter_cache_manager
description: Generic cache manager for flutter. Saves web files on the storages of the device and saves the cache info using sqflite.
version: 3.3.1
homepage: https://github.com/Baseflow/flutter_cache_manager/tree/develop/flutter_cache_manager
topics:
  - cache
  - cache-manager
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  clock: ^1.1.1
  collection: ^1.17.2
  file: ">=6.0.0 <=7.0.0"
  flutter:
    sdk: flutter
  http: ^1.1.0
  path: ^1.8.3
  path_provider: ^2.1.1
  rxdart: "^0.27.7"
  sqflite: ^2.3.0
  uuid: ^4.0.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  flutter_lints: ^2.0.3
